# Generated by Django 4.1.3 on 2022-11-11 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='dentistlog',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dentistlog',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dentistlog',
            name='last_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dentist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dentistlog',
            name='consultation_duration',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
