# Generated by Django 4.1.3 on 2022-11-12 00:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_appointment_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentistlog',
            old_name='ConsultationDetails',
            new_name='consultation_details',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='dentistlog',
            name='ConsultationDate',
        ),
        migrations.RemoveField(
            model_name='dentistlog',
            name='email',
        ),
        migrations.AddField(
            model_name='dentistlog',
            name='consultation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='dentistlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('root_canal_treatment', 'Root Canal Treatment'), ('impaction', 'Impaction'), ('tooth_pain', 'Tooth Pain'), ('cavity', 'Cavity'), ('filling', 'Filling'), ('crown_placement', 'Crown Placement')], max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
